---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on  Debian 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
