---
-
  become: true
  become_user: root
  hosts: all
  tasks:
    - name: "Download the new debian Key"
      shell: "wget https://packages.sury.org/php/apt.gpg -O /etc/apt/trusted.gpg.d/php-sury.gpg"

    - name: "Update apt repo and cache on Debian"
      apt: "update_cache=yes force_apt_get=yes cache_valid_time=3600"

    - name: "Upgrade all packages on servers"
      apt: "upgrade=dist force_apt_get=yes"

    - name: "Adding the extension=raphf.so to /etc/php/7.4/apache2/php.ini"
      lineinfile:
            path: /etc/php/7.4/apache2/php.ini
            line: "extension=raphf.so"
            state: present
            backup: yes
    - name: "Adding the extension=raphf.so to /etc/php/7.4/cli/php.ini"
      lineinfile:
            path: /etc/php/7.4/cli/php.ini
            line: "extension=raphf.so"
            state: present
            backup: yes
